
THUMBNAIL_SIZE = 500, 500
GEOMETRIC_INFER = "geometric"
HOOVERNET_INFER = "hoover"


INFERENCE_MODULE = GEOMETRIC_INFER


DEEPZOOM_TILE_SIZE = 254
DEEPZOOM_TILE_OVERLAP = 1
DEEPZOOM_DOWNSAMPLE_FACTOR = 4
DEEPZOOM_LIMIT_BOUNDS = True
DEEPZOOM_FORMAT = 'jpeg'
DEEPZOOM_TILE_QUALITY = 75

SLIDE_DIR = 'static/images/pathology'
SLIDE_CACHE_SIZE = 10

