
THUMBNAIL_SIZE = 500, 500
GEOMETRIC_INFER = "geometric"
HOVERNET_INFER = "hoover"
INFERENCE_URL = "http://hovernet.northeurope.azurecontainer.io"

INFERENCE_MODULE = HOVERNET_INFER

DEEPZOOM_TILE_SIZE = 254
DEEPZOOM_TILE_OVERLAP = 1
DEEPZOOM_DOWNSAMPLE_FACTOR = 4
DEEPZOOM_LIMIT_BOUNDS = True
DEEPZOOM_FORMAT = 'jpeg'
DEEPZOOM_TILE_QUALITY = 75

SLIDE_DIR = 'static/images'
SLIDE_CACHE_SIZE = 10

DOWNSAMPLE_FACTOR = 2