
MAX_INFERENCE_SIZE = 1960000
THUMBNAIL_SIZE = 500, 500
INFERENCE_URL = "http://hovernet.northeurope.azurecontainer.io"

DEEPZOOM_TILE_SIZE = 254
DEEPZOOM_TILE_OVERLAP = 1
DEEPZOOM_DOWNSAMPLE_FACTOR = 4
DEEPZOOM_LIMIT_BOUNDS = True
DEEPZOOM_FORMAT = 'jpeg'
DEEPZOOM_TILE_QUALITY = 75

SLIDE_DIR = 'static/images'
SLIDE_CACHE_SIZE = 10

DOWNSAMPLE_FACTOR = 2